USE AdventureWorks2008R2
GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN

UPDATE Production.Product
SET ListPrice=ListPrice*1.1
WHERE Name='Mountain-100'

WAITFOR DELAY '00:00:10'

COMMIT
GO